//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab3.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdOrder
    {
        public int ID { get; set; }
        public int OrdID { get; set; }
        public int ProdID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
